# Generated by Django 3.1.7 on 2021-03-09 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_for_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='complaint.useremail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useremail',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='useremail',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer')], max_length=140),
        ),
    ]
