# Generated by Django 3.1.7 on 2021-03-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_auto_20210309_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useremail',
            name='password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_status',
            field=models.CharField(choices=[('Reviewing', 'Reviewing'), ('Resovled', 'Resovled'), ('Canceled', 'Canceled')], max_length=140),
        ),
    ]
