# Generated by Django 3.1.7 on 2021-03-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_auto_20210310_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_for_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='complaint.useremail'),
        ),
    ]
