# Generated by Django 3.1.7 on 2021-03-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_auto_20210310_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_date',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_for_user',
        ),
    ]
