# Generated by Django 3.1.7 on 2021-03-15 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_auto_20210310_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_for_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='complaint.useremail'),
        ),
    ]
